### ISSUE TITLE
Use Euler angles instead of quaternion in config file

### ISSUE THREAD

**Issue by taz030485** [xyonico/CameraPlus#2]
I might be a better idea to save the Euler angles for the third person camera rotation to the ini file instead of the quaternion values themselves. Since it will be much more human readable for external editing verses the raw quaternion values. 

Which even most people using the don't understand the maths behind it (Speaking of which, your default values of (0.25,0,0,1) aren't valid (ie not a normalised length) and also result in the camera being upside down.

**Comment by taz030485** [comment]
Fixed in #4

**Comment by xyonico** [comment]
[Version 2.0.0](https://github.com/xyonico/CameraPlus/releases) has implemented Euler angles.
