### ISSUE TITLE
Broken with update v0.10.2

### ISSUE THREAD

**Issue by lululombard** [xyonico/CameraPlus#5]
Hi !
The update has broken CameraPlus, the camera is stuck in the ground :
![image](https://user-images.githubusercontent.com/2182934/42970090-49bee1a0-8ba0-11e8-9b45-fed358724169.png)

I'm using Beat Saber (Steam edition) on Windows 10 with an Oculus Rift CV1.

Thank you !

**Comment by xyonico** [comment]
This has been fixed with the newest release. Please run the mod installer again and get the newest release.
