### ISSUE TITLE
Steam link video output

### ISSUE THREAD

**Issue by PhilVon** [xyonico/CameraPlus#8]
The output that the steam link shows while in "VR mode" does not reflect that of what is on the computer and instead defaults to headset view, is it possible to force the steam link to show 3rd person view?

**Comment by xyonico** [comment]
There's definitely nothing I can do from the plugin to fix this, so I'm going to close this issue. As far as I know, there's no way to turn off the VR mode.

**Comment by PhilVon** [comment]
According to a response from a valve employee, the view is determined by the publisher, which granted is not you, but since you have already overridden the camera for desktop view it may still be possible to do this as part of the plugin. I'd have a look at the API's myself but am unfamiliar with steamworks in general. I'll keep digging about and if i can find something i'll get back to you.

valve employee's response on the issue: https://steamcommunity.com/app/353380/discussions/0/1368380934249831287/?tscn=1498375715

**Comment by xyonico** [comment]
They specifically say publisher instead of developer, because I think it's simply adding asymmetric gameplay support on the Steam page. That then explains how a Valve employee could turn that on. It's not likely they modified the build themselves.
